### ISSUE TITLE
Local path in Kanban-Board builds

### ISSUE THREAD

**Issue by MoritzKemp** [akless/ccm-components#1]
Both builds of the Kanban-Board component contain a local path in config: 
`https://akless.github.io/ccm-components/kanban_board/ccm.kanban_board.min.js` 
`https://akless.github.io/ccm-components/kanban_board/ccm.kanban_board.js`

Local path at: `"css": [ "ccm.load", "../kanban_board/resources/default.css" ]`

**Comment by akless** [comment]
Grundsätzlich handhabe ich das so das in den festen Versionsdateien absolute Pfade (für Live-Betrieb) und in den latest-Dateien relative Pfade (für Entwicklung/Testen) verwendet werden.

**Comment by akless** [comment]
Zum KanbanBoard gibt es noch keine offizielle v1.0.0 mit absoluten Pfaden. Das ist also noch nicht ganz fertig. Da fehlt noch das Löschen von Karten und ein paar andere Dinge.

**Comment by MoritzKemp** [comment]
Alles klar.
