### ISSUE TITLE
ccm.quiz.js: Info Box (i) neither fully viewable nor scrollable 

### ISSUE THREAD

**Issue by mkaul** [akless/ccm-components#6]
In ccm.quiz.js the Info Box under (i) is neither fully viewable nor scrollable 

![image](https://user-images.githubusercontent.com/1114169/36630985-5452397a-1970-11e8-94c2-3aa4fda4dfb1.png)

**Comment by akless** [comment]
The layout set here via the configuration of the quiz component is optimized for rather shorter tooltips. For more extensive tooltips, it needs a different layout.
